services:
  app:
    build:
      context: .
    container_name: app
    ports:
      - 3000:3000
    command: ['sh', '-c', 'npm run dev']
    develop:
      watch:
        - action: sync
          path: ./
          target: /home/node/app/
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
  storybook:
    build:
      context: .
    container_name: storybook
    ports:
      - 6006:6006
    command: ['sh', '-c', 'npm run storybook']
    develop:
      watch:
        - action: sync
          path: ./
          target: /home/node/app/
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
  ngrok:
    container_name: ngrok
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command: ['http', 'app:3000']
    ports:
      - 4040:4040
    depends_on:
      - app
    environment:
      - NGROK_AUTHTOKEN
