version: '3'

services:
  app:
    build:
      context: .
    container_name: app
    ports:
      - 3000:3000
    command: ['sh', '-c', 'npm run dev']
    volumes:
      - ./src:/home/node/app/src
      - ./public:/home/node/app/public
  storybook:
    build:
      context: .
    container_name: storybook
    ports:
      - 6006:6006
    command: ['sh', '-c', 'npm run storybook']
    volumes:
      - ./src:/home/node/app/src
      - ./public:/home/node/app/public
  ngrok:
    container_name: ngrok
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command: ['http', 'app:3000']
    ports:
      - 4040:4040
    depends_on:
      - app
    environment:
      - NGROK_AUTHTOKEN
