import Footer from 'components/layouts/Footer';
import Header from '../components/layouts/Header';
import './globals.css';
import { Alegreya_Sans_SC, Zen_Kaku_Gothic_Antique } from 'next/font/google';

const alegreyaSansSc = Alegreya_Sans_SC({ subsets: ['latin'], weight: ['400', '700'] });
const ZenkakuGothicAntique_normal = Zen_Kaku_Gothic_Antique({
  subsets: ['latin'],
  weight: ['400', '700'],
});

export const metadata = {
  title: "maybe-dog's portfolio",
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={ZenkakuGothicAntique_normal.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
