import Footer from 'components/layouts/Footer';
import Header from '../components/layouts/Header';
import './globals.css';
import { Noto_Sans_JP } from 'next/font/google';

const noto_sans_jp = Noto_Sans_JP({
  subsets: ['latin'],
  weight: ['400', '700'],
  preload: false,
});

export const metadata = {
  title: "maybe-dog's portfolio",
  description: 'Generated by create next app',
};

const links = [
  { name: 'Home', to: '/' },
  { name: 'Works', to: '/works' },
  { name: 'Timeline', to: '/timeline' },
];

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='ja'>
      <body className={`${noto_sans_jp.className} min-h-screen flex flex-col`}>
        <Header links={links} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
